name: Husbandry
version: '${version}'

main: me.beeliebub.husbandry.Husbandry
api-version: '26.1.1'
load: POSTWORLD

commands:
  husbandry:
    description: Husbandry admin commands
    usage: /husbandry <analyzer|editor|crop_analyzer|crop_editor|quality_wheat_feed|quality_carrot_feed|quality_golden_carrot_feed|quality_seed_feed|quality_crop>

permissions:
  husbandry.admin:
    description: Access to Husbandry admin commands
    default: op